# NumPy Array'i oluşturmak

In [1]:
import numpy as np

In [3]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [4]:
a=np.array([1,2,3,4,5])
type(a)

numpy.ndarray

In [7]:
np.array([3.14,4,2,13],dtype="float32")

array([ 3.14,  4.  ,  2.  , 13.  ], dtype=float32)

In [ ]:
# sıfırdan array olşturma işlemleri

In [12]:
np.zeros(10,dtype="int")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [19]:
np.ones((3,4),dtype="int")

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [21]:
np.full((3,5),7)

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [22]:
np.arange(0,31,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [23]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [24]:
np.random.normal(10,4,(3,4))

array([[-4.21029267, 11.06611982, 12.51811581,  8.04889708],
       [12.99025144, 13.22665181,  8.37423182, 10.967126  ],
       [ 9.77757882, 11.42432511, 10.67116024, 10.06569928]])

In [25]:
np.random.randint(0,10,(3,5))

array([[8, 4, 7, 5, 9],
       [4, 3, 1, 3, 3],
       [6, 2, 0, 7, 5]])

# Array Özellikleri

* **ndim** = boyut sayısı
* **shape** = boyut bilgisi
* **size** = toplam eleman sayısı
* **dtype** = array veri tipi 

In [26]:
import numpy as np

In [36]:
np.random.randint(10,size=10)

array([4, 7, 9, 7, 4, 3, 2, 6, 1, 1])

In [43]:
d = np.random.randint(10,size=10)

In [44]:
d.ndim

1

In [45]:
d.shape

(10,)

In [46]:
d.size

10

In [47]:
d.dtype

dtype('int32')

In [49]:
e = np.random.randint(10,size=(3,5))

In [50]:
e

array([[1, 7, 3, 2, 0],
       [5, 2, 7, 4, 2],
       [6, 7, 9, 1, 2]])

In [51]:
e.ndim

2

In [52]:
e.shape

(3, 5)

In [53]:
e.size

15

In [54]:
e.dtype

dtype('int32')

## Yeniden şekillendirme (reshaping)

In [2]:
import numpy as np 

In [5]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
a=np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
a.ndim

1

In [14]:
b=a.reshape((1,9))

In [15]:
b.ndim

2

## Array Birleştime(concatenation)

In [16]:
import numpy as np

In [19]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [20]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [22]:
z = np.array([7,8,9])

In [23]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# iki boyut

In [24]:
a = np.array([[1,2,3],
             [4,5,6]])

In [26]:
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [27]:
np.concatenate([a,a],axis= 1 )

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [35]:
b = np.random.randint(1,10,(3,5))
c = np.random.randint(1,10,(3,4))
np.concatenate([b,c],axis=1)

array([[6, 9, 6, 5, 1, 4, 6, 7, 2],
       [4, 8, 2, 3, 8, 2, 9, 5, 4],
       [7, 8, 3, 6, 7, 9, 2, 6, 8]])

## Array Ayırma (splitting)

In [37]:
x = np.array([1,2,3,99,99,3,2,1])

In [38]:
np.split(x,[3,5])

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [40]:
a,b,c = np.split(x,[3,5])

In [41]:
a

array([1, 2, 3])

In [42]:
b

array([99, 99])

In [43]:
c

array([3, 2, 1])

In [ ]:
# iki boyutlu ayırma

In [45]:
m =  np.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [52]:
np.vsplit(m,[2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [53]:
ust,alt = np.vsplit(m,[2])

In [54]:
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [55]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [56]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [57]:
np.hsplit(m,[3])

[array([[ 0,  1,  2],
        [ 4,  5,  6],
        [ 8,  9, 10],
        [12, 13, 14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [58]:
sag,sol = np.hsplit(m,[3])

In [59]:
sag

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

In [60]:
sol

array([[ 3],
       [ 7],
       [11],
       [15]])

## Array Sıralama (Sorting)

In [61]:
import numpy as np 

In [71]:
v = np.array([5,6,3,2,0,9,1,7])
v

array([5, 6, 3, 2, 0, 9, 1, 7])

In [72]:
np.sort(v)

array([0, 1, 2, 3, 5, 6, 7, 9])

In [73]:
v

array([5, 6, 3, 2, 0, 9, 1, 7])

In [74]:
v.sort()

In [75]:
v

array([0, 1, 2, 3, 5, 6, 7, 9])

In [76]:
# iki boyutlu array sıralama

In [81]:
m = np.random.normal(20,5,(3,3))
m

array([[28.473304  , 22.81850192, 15.11496237],
       [23.8746232 , 17.47106983, 15.67507434],
       [23.48805304, 28.52897538, 24.13927553]])

In [82]:
np.sort(m,axis=1)

array([[15.11496237, 22.81850192, 28.473304  ],
       [15.67507434, 17.47106983, 23.8746232 ],
       [23.48805304, 24.13927553, 28.52897538]])

In [83]:
np.sort(m,axis=0)

array([[23.48805304, 17.47106983, 15.11496237],
       [23.8746232 , 22.81850192, 15.67507434],
       [28.473304  , 28.52897538, 24.13927553]])

 #### **not :** 
 * axis = 1 --> satır
 * axis = 0 --> sütün

## Index ile Elemanlara Erişmek

In [8]:
import numpy as np 
n = np.random.randint(10,size=10)
n

array([3, 3, 4, 8, 6, 2, 2, 6, 0, 1])

In [9]:
n[0]

3

In [10]:
n[-4]

2

In [11]:
n[0] = 45
n

array([45,  3,  4,  8,  6,  2,  2,  6,  0,  1])

In [15]:
m = np.random.randint(10,size=(3,5))
m

array([[8, 9, 0, 3, 2],
       [9, 4, 7, 4, 1],
       [7, 0, 7, 6, 4]])

In [16]:
m[0,0]

8

In [17]:
m[1,1]

4

In [18]:
m[1,2]

7

In [20]:
m[1,2] = 99
m

array([[ 8,  9,  0,  3,  2],
       [ 9,  4, 99,  4,  1],
       [ 7,  0,  7,  6,  4]])

In [23]:
m[1,4] = 2.99
m

array([[ 8,  9,  0,  3,  2],
       [ 9,  4, 99,  4,  2],
       [ 7,  0,  7,  6,  4]])

In [ ]:
# sonradan eklendiği için integere çevirdi

#  
###  Slicing ile Elemanlara Erişmek ( Array Alt Kümesine Erişmek) 


In [ ]:
import numpy as np

In [24]:
a = np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [25]:
a[0:3]

array([20, 21, 22])

In [26]:
a[:3]

array([20, 21, 22])

In [27]:
a[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [28]:
a[1::2]

array([21, 23, 25, 27, 29])

In [29]:
a[0::2]

array([20, 22, 24, 26, 28])

In [30]:
a[2::2]

array([22, 24, 26, 28])

In [31]:
a[0::3]

array([20, 23, 26, 29])

In [37]:
a[-5:-1]

array([25, 26, 27, 28])

In [40]:
a[-6::2]

array([24, 26, 28])

In [42]:
a[:-1]

array([20, 21, 22, 23, 24, 25, 26, 27, 28])

In [57]:
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [63]:
a[::-1]

array([29, 28, 27, 26, 25, 24, 23, 22, 21, 20])

In [32]:
# iki boyutlu slice işlemleri

In [35]:
m = np.random.randint(10,size = (5,5))
m

array([[5, 2, 8, 0, 8],
       [3, 1, 2, 3, 8],
       [1, 3, 0, 9, 0],
       [8, 4, 9, 2, 5],
       [6, 5, 6, 0, 9]])

In [43]:
m[:,0]

array([5, 3, 1, 8, 6])

In [44]:
m[:,1]

array([2, 1, 3, 4, 5])

In [45]:
m[:,4]

array([8, 8, 0, 5, 9])

In [46]:
m[2,3]

9

In [47]:
m

array([[5, 2, 8, 0, 8],
       [3, 1, 2, 3, 8],
       [1, 3, 0, 9, 0],
       [8, 4, 9, 2, 5],
       [6, 5, 6, 0, 9]])

In [48]:
m[0,:]

array([5, 2, 8, 0, 8])

In [49]:
m[3,:]

array([8, 4, 9, 2, 5])

In [50]:
m[3]

array([8, 4, 9, 2, 5])

In [51]:
m

array([[5, 2, 8, 0, 8],
       [3, 1, 2, 3, 8],
       [1, 3, 0, 9, 0],
       [8, 4, 9, 2, 5],
       [6, 5, 6, 0, 9]])

In [54]:
m[0:4,3:]

array([[0, 8],
       [3, 8],
       [9, 0],
       [2, 5]])

In [56]:
m[::,:2]  # m[:,:2] aynı

array([[5, 2],
       [3, 1],
       [1, 3],
       [8, 4],
       [6, 5]])

In [65]:
m[1:3,:2] # m[1:3,0:2]

array([[3, 1],
       [1, 3]])

#      
## Alt Küme Üzerinde İşlem Yapmak 

In [1]:
import numpy as np
a = np.random.randint(10,size=(5,5))
a

array([[0, 9, 9, 7, 0],
       [8, 1, 3, 6, 7],
       [7, 0, 2, 8, 9],
       [6, 4, 5, 8, 1],
       [2, 1, 2, 7, 6]])

In [2]:
alt_a = a[0:3,0:2]
alt_a

array([[0, 9],
       [8, 1],
       [7, 0]])

In [3]:
alt_a[0,0] = 9999
alt_a[1,1] = 555

In [4]:
alt_a

array([[9999,    9],
       [   8,  555],
       [   7,    0]])

In [5]:
a

array([[9999,    9,    9,    7,    0],
       [   8,  555,    3,    6,    7],
       [   7,    0,    2,    8,    9],
       [   6,    4,    5,    8,    1],
       [   2,    1,    2,    7,    6]])

In [6]:
m = np.random.randint(10,size=(5,5))
m

array([[5, 5, 0, 4, 4],
       [5, 8, 0, 4, 5],
       [6, 7, 9, 9, 7],
       [8, 7, 5, 2, 1],
       [7, 4, 9, 1, 1]])

In [14]:
alt_b = m[0:3,0:2].copy()

In [15]:
alt_b

array([[5, 5],
       [5, 8],
       [6, 7]])

In [16]:
alt_b[0,0] = 9999

In [17]:
alt_b

array([[9999,    5],
       [   5,    8],
       [   6,    7]])

In [18]:
m

array([[5, 5, 0, 4, 4],
       [5, 8, 0, 4, 5],
       [6, 7, 9, 9, 7],
       [8, 7, 5, 2, 1],
       [7, 4, 9, 1, 1]])

In [20]:
alt_b*3

array([[29997,    15],
       [   15,    24],
       [   18,    21]])

#     
## Fancy İndex ile Elemanlara Erişmek

In [21]:
import numpy as np
v = np.arange(0,30,3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [22]:
v[1]

3

In [23]:
v[3]

9

In [24]:
v[5]

15

In [25]:
[v[1],v[3],v[5]]

[3, 9, 15]

In [27]:
al_getir = [1,3,5]

In [28]:
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [29]:
v[al_getir]

array([ 3,  9, 15])

In [ ]:
# iki boyutta fancy

In [32]:
m = np.arange(9).reshape((3,3))

In [33]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [35]:
satır = np.array([0,1])
sutun = np.array([1,2])

In [36]:
m[satır,sutun]

array([1, 5])

In [37]:
# basit index ile fancy index

In [38]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [39]:
m[2,[1,2]]

array([7, 8])

In [45]:
# slice ile fancy

In [41]:
m[:3,[1,2]] # m[0:,[1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [44]:
m[1:2,[1,2]]

array([[4, 5]])

#   
## Koşullu Eleman İşlemleri

In [46]:
import numpy as np
v = np.array([1,2,3,4,5])

In [47]:
v < 3

array([ True,  True, False, False, False])

In [48]:
v[v < 3]

array([1, 2])

In [49]:
v[v >= 3]

array([3, 4, 5])

In [58]:
v[v == 3]

array([3])

In [59]:
v[v != 3]

array([1, 2, 4, 5])

In [60]:
v

array([1, 2, 3, 4, 5])

In [61]:
v*2

array([ 2,  4,  6,  8, 10])

In [62]:
v/5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [63]:
v*5/10

array([0.5, 1. , 1.5, 2. , 2.5])

In [64]:
v**2

array([ 1,  4,  9, 16, 25], dtype=int32)

## Matematiksel İşlemler 

In [67]:
import numpy as np
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [68]:
a-1

array([0, 1, 2, 3, 4])

In [69]:
a*5

array([ 5, 10, 15, 20, 25])

In [70]:
a/3

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667])

In [73]:
a*5/10 -1

array([-0.5,  0. ,  0.5,  1. ,  1.5])

In [74]:
# ufunc

In [78]:
a

array([1, 2, 3, 4, 5])

In [76]:
np.subtract(a,1)

array([0, 1, 2, 3, 4])

In [79]:
np.add(a,5)

array([ 6,  7,  8,  9, 10])

In [82]:
np.multiply(a,5)

array([ 5, 10, 15, 20, 25])

In [83]:
np.divide(a,3)

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667])

In [84]:
a**2

array([ 1,  4,  9, 16, 25], dtype=int32)

In [85]:
a**3

array([  1,   8,  27,  64, 125], dtype=int32)

In [86]:
np.power(a,4)

array([  1,  16,  81, 256, 625], dtype=int32)

In [87]:
a % 2

array([1, 0, 1, 0, 1], dtype=int32)

In [88]:
np.mod(a,2)

array([1, 0, 1, 0, 1], dtype=int32)

In [92]:
np.absolute(np.array([-3]))

array([3])

In [93]:
np.sin(90)

0.8939966636005579

In [98]:
np.cos(180)

-0.5984600690578581

In [99]:
v = np.array([1,2,3])

In [100]:
np.log(v)

array([0.        , 0.69314718, 1.09861229])

In [101]:
np.log2(v)

array([0.       , 1.       , 1.5849625])

In [102]:
np.log10(v)

array([0.        , 0.30103   , 0.47712125])

In [103]:
?np

Type:        module
String form: <module 'numpy' from 'C:\\Users\\Fettah\\pyhton\\lib\\site-packages\\numpy\\__init__.py'>
File:        c:\users\fettah\pyhton\lib\site-packages\numpy\__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://www.scipy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x

In [104]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_ad

In [105]:
# cheat sheet  (kopya kağıdı)

In [106]:
v

array([1, 2, 3])

In [107]:
np.mean(v)

2.0

In [108]:
v.max()

3

In [110]:
v.min()

1

In [111]:
v.sum()

6

In [112]:
np.var(v)

0.6666666666666666

In [113]:
np.std(v)

0.816496580927726

## NumPy ile İki Bilinmeyenli Denklem Çözümü

In [116]:
import numpy as np

 >**5 * x0 + x1 = 12**
 
 >**x0 + 3 * x1 = 10**


In [122]:
a = np.array([[5,1],[1,3]])
b = np.array([12,10])
a,b

(array([[5, 1],
        [1, 3]]),
 array([12, 10]))

In [123]:
x = np.linalg.solve(a,b)
x

array([1.85714286, 2.71428571])